### ISSUE TITLE
UTF8 encoding issue

### ISSUE THREAD

**Issue by jbransen** [winterland1989/mysql-haskell#9]
Consider the following program:

```
{-# LANGUAGE OverloadedStrings #-}

module Main where

import Data.Text
import Database.MySQL.Base

import Control.Monad

str :: Text
str = "Strange character: 👌"

main :: IO () 
main = do
  conn <- connect
    defaultConnectInfo {ciUser = "testuser", ciPassword = "testpassword", ciDatabase = "testdb"}
  execute_ conn "CREATE TABLE IF NOT EXISTS `testtable` (\
                \`ID` int(10) unsigned NOT NULL AUTO_INCREMENT,\
                \`testfield` varchar(50) DEFAULT NULL,\
                \PRIMARY KEY (`ID`)\
                \)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4"
  void $ execute conn "INSERT INTO testtable (`testfield`) VALUES (?)" [MySQLText str]
```

This results in an exception:
`*** Exception: ERRException (ERR {errCode = 1366, errState = "22007", errMsg = "Incorrect string value: '\\xF0\\x9F\\x91\\x8C' for column 'testfield' at row 1"})`

The utf8mb4 charset does however support this character, and executing this query in other ways does succeed.

**Comment by winterland1989** [comment]
The problem is that currently [i fixed connection charset to 'utf8'](https://github.com/winterland1989/mysql-haskell/blob/master/Database/MySQL/Protocol/Auth.hs#L191). we can move charset option into `ConnInfo`, I'll try to find time do it.

**Comment by jbransen** [comment]
Ah right, but utf8 in MySQL is not really UTF8, it's just a bad name for a subset of it. Either hardcoding to utf8mb4 or making this a field of `ConnInfo` sound fine.

**Comment by winterland1989** [comment]
done in bac3c6dc831d58ecb4b348dce325897ce7c96416, can you help me to confirm master works?

**Comment by jbransen** [comment]
Confirmed that setting `ciCharset = 224` works, but it seems that you forgot to export `utf8_general_ci` and `utf8mb4_unicode_ci`.

**Comment by winterland1989** [comment]
I'll export them and cut a release soon.
